# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - ur20_shoulder_pan_joint
      - ur20_shoulder_lift_joint
      - ur20_elbow_joint
      - ur20_wrist_1_joint
      - ur20_wrist_2_joint
      - ur20_wrist_3_joint