---
name: pre-commit
on:
  pull_request:
jobs:
  pre-commits:
    name: pre-commit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: "Install dependencies"
        run: |
          python -m pip install catkin_lint
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --hook-stage manual
