---
name: Pull Request Docs Check

on:
  push:
    branches:
      - main
      - ros2
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "./ur_documentation/docs"
