---
name: Pull Request Docs Check

on:
  push:
    branches:
      - main
      - ros2
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install sphinx-rtd-theme sphinx
      - name: Build documentation
        run: |
          cd ur_documentation/docs
          make html
